### ISSUE TITLE
UR5 arm is protective stopped during execution without touching any obstacles

### ISSUE THREAD

**Issue by shinian123** [ros-industrial/ur_modern_driver#195]
Our lab use ROS operating system to operate UR5 arms using moveit. Recently,we encounterd a problem when the UR5 arms get protective stop during execution. While the arm does not touch any obstacles.

Our joint_limits.yaml is :
```yaml
joint_limits:
left_arm_elbow_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
left_arm_shoulder_lift_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
left_arm_shoulder_pan_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
left_arm_wrist_1_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
left_arm_wrist_2_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
left_arm_wrist_3_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
right_arm_elbow_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
right_arm_shoulder_lift_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
right_arm_shoulder_pan_joint:
has_velocity_limits: true
max_velocity: 3.15
has_acceleration_limits: false
max_acceleration: 0
right_arm_wrist_1_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
right_arm_wrist_2_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
right_arm_wrist_3_joint:
has_velocity_limits: true
max_velocity: 3.2
has_acceleration_limits: false
max_acceleration: 0
```

It seems when the speed of the arms changed drastically , the protective stop program will be triggered.
We think the problem is due to some parameters of joint_limits.yaml is not correctly set, but we don't know how to tune these parameters.Could any one help us? Thanks.
