### ISSUE TITLE
Documentation on using `controllers.yaml` correctly with `ros_control`

### ISSUE THREAD

**Issue by ri-ceres** [ros-industrial/ur_modern_driver#305]
Following the documentation in the [README.md](https://github.com/ros-industrial/ur_modern_driver/tree/kinetic-devel#usage), I am trying to configure `ros_control` using the configuration provided by the *MoveIt! Setup Assistant*.  I am using ROS Kinetic and have the goal of trying to continuously control a UR5e with a Robotiq 2f-140 gripper. 

The *MoveIt! Setup Assistant* does not output a `config/controllers.yaml`, but does create `config/ros_controllers.yaml`, while the ur_modern [README.md](https://github.com/ros-industrial/ur_modern_driver/tree/kinetic-devel#usage) specifies to "add the desired controller to the `controllers.yaml` in the `urXX_moveit_config/config` folder". This seems to imply that this modification should be appended to the `config/ros_controllers.yaml` that is generated by the *MoveIt! Setup Assistant*.

This makes sense because it looks similar to the existing `ur_modern_driver/config/ur5e_controllers.yaml`. So, by copying the content into a new file called `my_robot_moveit_config/config/controllers.yaml` and adding the `controller_list:` needed for ROS control, we should have the necessary changes.

Finally, modifying the paths in `ur_modern_driver/launch/ur5e_ros_control.launch` to reflect the path of the new configuration should load the `ros_control` config :

```
  <rosparam file="$(find my_robot_moveit_config)/config/controllers.yaml" command="load"/>
```

However, following this logic, the `controller_manager` can't spawn `/follow_joint_trajectory`:

[ERROR] [1557271637.324512055]: Could not load controller 'follow_joint_trajectory' because the type was not specified. Did you load the controller configuration on the parameter server (namespace: '/follow_joint_trajectory')? 

Are the instructions for using `ros_control` incomplete, or am I interpreting them incorrectly? I have found other issues such as [#261](https://github.com/ros-industrial/ur_modern_driver/issues/261), but they don't provide any more details.

For reference, my new `my_robot_moveit_config/config/controllers.yaml` looks like this:

```
      # MoveIt-specific simulation settings
      moveit_sim_hw_interface:
        joint_model_group: controllers_initial_group_
        joint_model_group_pose: controllers_initial_pose_
      # Settings for ros_control control loop
      generic_hw_control_loop:
        loop_hz: 500
        cycle_time_error_threshold: 0.01
      # Settings for ros_control hardware interface
      hardware_interface:
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint
          - finger_joint
        sim_control_mode: 1  # 0: position, 1: velocity
      # Publish all joint states
      # Creates the /joint_states topic necessary in ROS
      joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 500
      controller_list:
        - name: ""
          action_ns: gripper
          type: GripperCommand
          default: true
          joints:
            - finger_joint
        - name: /pos_based_pos_traj_controller
          action_ns: follow_joint_trajectory
          default: True
          type: FollowJointTrajectory
          joints:
            - shoulder_pan_joint
            - shoulder_lift_joint
            - elbow_joint
            - wrist_1_joint
            - wrist_2_joint
            - wrist_3_joint
      pos_based_pos_traj_controller:
        type: position_controllers/JointTrajectoryController
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint
        constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
          shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
          elbow_joint: {trajectory: 0.1, goal: 0.1}
          wrist_1_joint: {trajectory: 0.1, goal: 0.1}
          wrist_2_joint: {trajectory: 0.1, goal: 0.1}
          wrist_3_joint: {trajectory: 0.1, goal: 0.1}
        stop_trajectory_duration: 0.5
        state_publish_rate:  500
        action_monitor_rate: 10
        gains:
          shoulder_pan_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          shoulder_lift_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          elbow_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          wrist_1_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          wrist_2_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          wrist_3_joint:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
      vel_based_pos_traj_controller:
         type: velocity_controllers/JointTrajectoryController
         joints:
           - shoulder_pan_joint
           - shoulder_lift_joint
           - elbow_joint
           - wrist_1_joint
           - wrist_2_joint
           - wrist_3_joint
         constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
            shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
            shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
            elbow_joint: {trajectory: 0.1, goal: 0.1}
            wrist_1_joint: {trajectory: 0.1, goal: 0.1}
            wrist_2_joint: {trajectory: 0.1, goal: 0.1}
            wrist_3_joint: {trajectory: 0.1, goal: 0.1}
         stop_trajectory_duration: 0.5
         state_publish_rate:  500
         action_monitor_rate: 10
         gains:
            #!!These values have not been optimized!!
            shoulder_pan_joint:  {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
            shoulder_lift_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
            elbow_joint:         {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
            wrist_1_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
            wrist_2_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
            wrist_3_joint:       {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
         # Use a feedforward term to reduce the size of PID gains
         velocity_ff:
            shoulder_pan_joint: 1.0
            shoulder_lift_joint: 1.0
            elbow_joint: 1.0
            wrist_1_joint: 1.0
            wrist_2_joint: 1.0
            wrist_3_joint: 1.0
         state_publish_rate:  500
```
